export const API_ERROR_CODES = [
  "UNAUTHORIZED",
  "FORBIDDEN",
  "NOT_FOUND",
  "VALIDATION_ERROR",
  "RATE_LIMIT_EXCEEDED",
  "COST_LIMIT_EXCEEDED",
  "USAGE_LIMIT_EXCEEDED",
  "RESOURCE_LIMIT_EXCEEDED",
  "AI_OUTPUT_INVALID",
  "SAFETY_BLOCKED",
  "COMPLIANCE_BLOCKED",
  "PROCESSING_FAILED",
  "WEBHOOK_VERIFICATION_FAILED",
  "INTERNAL_ERROR",
] as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[number];
