name: Bug Report
description: 不具合報告
title: "[Bug] "
labels: ["type:bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期待する挙動
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 実際の挙動
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - low
        - medium
        - high
        - critical
    validations:
      required: true
