name: Bug
description: Report a bug
title: "[Bug] "
labels: [type:bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
