export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",

  AI_PROVIDER_ERROR: "AI_PROVIDER_ERROR",
  AI_PROVIDER_TIMEOUT: "AI_PROVIDER_TIMEOUT",
  AI_OUTPUT_INVALID: "AI_OUTPUT_INVALID",
  SAFETY_FAILED: "SAFETY_FAILED",

  RATE_LIMITED: "RATE_LIMITED",
  COST_LIMIT_EXCEEDED: "COST_LIMIT_EXCEEDED",
  FEATURE_DISABLED: "FEATURE_DISABLED",

  DATABASE_ERROR: "DATABASE_ERROR",
  PROCESSING_FAILED: "PROCESSING_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
