#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

SERVICE_NAME="ruletrade-ai.service"
UNIT_PATH="/etc/systemd/system/$SERVICE_NAME"
BUILD_DIR=".next-systemd"
EXPECTED_PROXY="http://127.0.0.1:3000"
NODE_BIN=""
NODE_BIN_DIR=""
NPM_BIN=""

fail() {
  printf '\n%s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

ensure_host_systemd() {
  local pid1 container_kind
  pid1="$(ps -p 1 -o comm= 2>/dev/null | tr -d '[:space:]' || true)"
  if ! command -v systemctl >/dev/null 2>&1 || [[ "$pid1" != "systemd" ]] || ! systemctl show-environment >/dev/null 2>&1; then
    fail "This shell cannot reach the host systemd manager (PID 1: ${pid1:-unknown}). Run this script from a terminal on the host machine, not from a container or Codex sandbox."
  fi
  if command -v systemd-detect-virt >/dev/null 2>&1; then
    if container_kind="$(systemd-detect-virt --container 2>/dev/null)"; then
      fail "This shell is running inside a detected container ($container_kind). Run this script from a terminal on the host machine."
    fi
  fi
}

ensure_tailscale_connected() {
  local status
  command -v tailscale >/dev/null 2>&1 || fail "The Tailscale CLI is missing. This script will not install it; restore the existing setup and rerun."
  command -v timeout >/dev/null 2>&1 || fail "The timeout utility is required to check the existing Tailscale daemon safely."
  command -v python3 >/dev/null 2>&1 || fail "python3 is required to inspect Tailscale status without printing device details."
  sudo -v || fail "sudo authorization is required to inspect the existing Tailscale daemon on this Linux host."
  status="$(timeout 5s sudo tailscale status --json 2>/dev/null)" || fail "The connected Tailscale daemon could not be verified. This script will not run tailscale up, log in, or reset Tailscale."
  printf '%s' "$status" | python3 -c 'import json,sys; d=json.load(sys.stdin); sys.exit(0 if d.get("BackendState") == "Running" and d.get("Self", {}).get("Online", False) else 1)' >/dev/null 2>&1 || fail "Tailscale is not connected. Restore the existing connection manually, then rerun."
}

select_node_24() {
  local nvm_script="$HOME/.nvm/nvm.sh"
  if command -v node >/dev/null 2>&1 && [[ "$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || true)" == "24" ]]; then
    NODE_BIN="$(command -v node)"
  else
    [[ -s "$nvm_script" ]] || fail "This host setup uses Node.js 24, but Node 24 and nvm were not found. Install nvm and Node 24, then rerun."
    # shellcheck disable=SC1090
    source "$nvm_script"
    if ! nvm use 24 >/dev/null 2>&1; then
      if confirm "Node 24 is not installed in nvm. Install the current Node 24 release now?"; then
        nvm install 24 >/dev/null || fail "nvm could not install Node 24. Check the network and nvm installation, then rerun."
        nvm use 24 >/dev/null || fail "nvm installed Node 24 but could not activate it."
      else
        fail "Install Node 24 with nvm, then rerun this script."
      fi
    fi
    NODE_BIN="$(command -v node)"
  fi
  NODE_BIN_DIR="$(dirname -- "$NODE_BIN")"
  NPM_BIN="$NODE_BIN_DIR/npm"
  [[ -x "$NPM_BIN" ]] || fail "npm was not found beside the selected Node 24 binary at $NODE_BIN_DIR."
  [[ "$("$NODE_BIN" -p 'process.versions.node.split(".")[0]')" == "24" ]] || fail "The selected runtime is not Node.js 24."
}

render_unit() {
  local target="$1"
  cat > "$target" <<UNIT_EOF
# Managed by scripts/setup-systemd-tailscale.sh
[Unit]
Description=Ruletrade-AI personal decision journal
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=$(id -un)
Group=$(id -gn)
WorkingDirectory=$REPO_ROOT
Environment=PATH=$NODE_BIN_DIR:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Environment=NEXT_DIST_DIR=$BUILD_DIR
Restart=on-failure
RestartSec=5
ExecStart=$NPM_BIN run start -- --hostname 127.0.0.1 --port 3000

[Install]
WantedBy=multi-user.target
UNIT_EOF
}

stage "Preflight and production build"
say "This setup needs the host's systemd manager and sudo. It will not install, log in to, or reset Tailscale."
ensure_host_systemd
command -v sudo >/dev/null 2>&1 || fail "sudo is required to install a system-wide service."
[[ "$(id -un)" != "root" ]] || fail "Run this wizard as the repository owner, not as root; it will request sudo only for systemd changes."
[[ "$(stat -c '%U' "$REPO_ROOT")" == "$(id -un)" ]] || fail "Run this wizard as the owner of $REPO_ROOT so the service can read the repository and .env.local."
command -v curl >/dev/null 2>&1 || fail "curl is required for the local health check."
[[ -f .env.local ]] || fail "The existing .env.local file is missing. Create it with GEMINI_API_KEY and GEMINI_MODEL, then rerun; this script will never read or edit it."
[[ -x node_modules/.bin/next ]] || fail "Dependencies are missing. Run npm install in the repository, then rerun."
git check-ignore -q "$BUILD_DIR/BUILD_ID" || fail "$BUILD_DIR is not ignored by git; refusing to place build output in a trackable path."
ensure_tailscale_connected
select_node_24
say "Using Node.js $($NODE_BIN -v) from $NODE_BIN."
if systemctl is-active --quiet "$SERVICE_NAME" && [[ -d "$BUILD_DIR" ]]; then
  say "The existing service is active; keeping its current build to avoid replacing files used by the running server."
else
  step "Rebuilding better-sqlite3 for the selected Node 24 runtime."
  "$NPM_BIN" rebuild better-sqlite3
  step "Building Next.js into the dedicated ignored directory $BUILD_DIR."
  NEXT_DIST_DIR="$BUILD_DIR" "$NPM_BIN" run build
fi

stage "Install and enable the systemd service"
say "The service runs as $(id -un) and binds only to 127.0.0.1:3000. It honors RULETRADE_DATABASE_PATH from the existing .env.local; otherwise the app uses .data/ruletrade-mvp.sqlite."
say "Next.js loads .env.local at runtime from this repository. The unit has no secret values and does not copy or edit .env.local."
say "Unmanaged units are left untouched. Existing units created by this script require confirmation before replacement."
UNIT_CANDIDATE="$(mktemp)"
trap 'rm -f "$UNIT_CANDIDATE"' EXIT
render_unit "$UNIT_CANDIDATE"
if [[ -e "$UNIT_PATH" ]] && ! cmp -s "$UNIT_CANDIDATE" "$UNIT_PATH"; then
  grep -q '^# Managed by scripts/setup-systemd-tailscale.sh$' "$UNIT_PATH" || fail "An unmanaged $UNIT_PATH exists. It was left untouched; inspect it manually before proceeding."
  confirm "Replace the existing Ruletrade-AI unit created by this script? It will reload and restart that service." || fail "The existing unit was left unchanged."
  sudo -v || fail "sudo authorization failed."
  sudo install -o root -g root -m 0644 "$UNIT_CANDIDATE" "$UNIT_PATH" || fail "Could not install the systemd unit."
  sudo systemctl daemon-reload || fail "systemd could not reload its unit files."
  sudo systemctl enable --now "$SERVICE_NAME" || fail "systemd could not enable and start $SERVICE_NAME."
elif [[ ! -e "$UNIT_PATH" ]]; then
  confirm "Install and enable the $SERVICE_NAME system service now?" || fail "No systemd files were changed."
  sudo -v || fail "sudo authorization failed."
  sudo install -o root -g root -m 0644 "$UNIT_CANDIDATE" "$UNIT_PATH" || fail "Could not install the systemd unit."
  sudo systemctl daemon-reload || fail "systemd could not reload its unit files."
  sudo systemctl enable --now "$SERVICE_NAME" || fail "systemd could not enable and start $SERVICE_NAME."
else
  say "The generated unit matches the installed unit; leaving its file unchanged."
  sudo systemctl enable --now "$SERVICE_NAME" || fail "systemd could not enable and start $SERVICE_NAME."
fi

stage "Verify the local service"
say "Waiting up to 30 seconds for Ruletrade-AI to respond on loopback."
for _ in {1..30}; do
  if systemctl is-active --quiet "$SERVICE_NAME" && curl --silent --fail --output /dev/null http://127.0.0.1:3000/; then
    say "The systemd service is active and the local HTTP check passed."
    break
  fi
  sleep 1
done
if ! systemctl is-active --quiet "$SERVICE_NAME" || ! curl --silent --fail --output /dev/null http://127.0.0.1:3000/; then
  fail "The service did not become healthy. Inspect it with: sudo journalctl -u $SERVICE_NAME -n 80 --no-pager"
fi

stage "Configure tailnet-only HTTPS with Tailscale Serve"
ensure_tailscale_connected
SERVE_STATUS="$(timeout 5s sudo tailscale serve status --json 2>/dev/null)" || fail "Could not inspect current Tailscale Serve configuration; leaving it unchanged."
SERVE_STATE="$(printf '%s' "$SERVE_STATUS" | python3 -c '
import json,sys
d=json.load(sys.stdin)
target="http://127.0.0.1:3000"
def values(x):
    if isinstance(x,dict):
        for v in x.values(): yield from values(v)
    elif isinstance(x,list):
        for v in x: yield from values(v)
    else:
        yield x
all_values=[str(v) for v in values(d)]
def walk(x):
    if isinstance(x,dict):
        for k,v in x.items():
            yield k.lower(),v
            yield from walk(v)
    elif isinstance(x,list):
        for v in x: yield from walk(v)
def configured(x):
    if isinstance(x,dict): return any(configured(v) for v in x.values())
    if isinstance(x,list): return any(configured(v) for v in x)
    return bool(x)
items=list(walk(d))
if any(k == "allowfunnel" and configured(v) for k,v in items): print("funnel")
elif any(target in v for v in all_values): print("same")
elif any(k in ("web","tcp") and configured(v) for k,v in items): print("other")
else: print("empty")
' 2>/dev/null)" || fail "Could not safely interpret current Tailscale Serve configuration; leaving it unchanged."
if [[ "$SERVE_STATE" == "funnel" ]]; then
  fail "A Funnel-enabled Tailscale route was detected. It was left untouched; review it manually before configuring a tailnet-only route."
elif [[ "$SERVE_STATE" == "other" ]]; then
  fail "An existing Tailscale Serve configuration was detected. It was left untouched; review it manually before rerunning."
elif [[ "$SERVE_STATE" == "same" ]]; then
  say "The expected Tailscale Serve route already exists; leaving the current Serve configuration unchanged."
else
  say "This adds a persistent HTTPS endpoint within the tailnet and forwards it to the loopback-only app. It does not enable public Funnel access."
  confirm "Configure Tailscale Serve for this device using $EXPECTED_PROXY?" || fail "Tailscale Serve was left unchanged."
  sudo tailscale serve --bg --https=443 "$EXPECTED_PROXY" || fail "Tailscale Serve could not be configured. Existing configuration was not reset."
fi
say "On a device connected to the same tailnet, open the HTTPS address shown by: sudo tailscale serve status"
say "Serve's --bg setting persists across reboot and Tailscale restarts."
say "The host must remain powered on, awake, and connected to Tailscale for the app to be reachable. This wizard does not change host power settings."
finish
