-- ============================================================
-- AI Run Logs / Observability MVP (Issue #51)
-- NOTE: Table definitions merged into 20260515000000_ai_run_logs_schema.sql
-- ============================================================
